server:
  port: 8080 # ECS Task Definition의 portMappings와 일치

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: # 구체적일수록 위에 작성하기
        # -----------------------------------------------
        # 1. Health Checks  (서비스별로 하나씩 보유, e.g /api/v1/{서비스명}/actuator/health)
        # -----------------------------------------------
        - id: member-service-health
          uri: http://member:8080 # Service Connect의 "검색 이름" (예: member)으로 사용
          predicates:
            - Path=/api/v1/members/actuator/health
          filters:
            - RewritePath=/api/v1/members/actuator/health, /actuator/health

        - id: store-service-health
          uri: http://store:8080
          predicates:
            - Path=/api/v1/stores/actuator/health
          filters:
            - RewritePath=/api/v1/stores/actuator/health, /actuator/health

        - id: coupon-service-health
          uri: http://coupon:8080
          predicates:
            - Path=/api/v1/coupons/actuator/health
          filters:
            - RewritePath=/api/v1/coupons/actuator/health, /actuator/health

        # -----------------------------------------------
        # 2. General API Routes (범용 경로)
        # -----------------------------------------------
        - id: member-service-api
          uri: http://member:8080 # Service Connect 이름
          predicates:
            - Path=/api/v1/auth/**
            - Path=/api/v1/members/**

        - id: store-service-api
          uri: http://store:8080 # Service Connect 이름
          predicates:
            - Path=/api/v1/owner/stores/**
            - Path=/api/v1/owners/**
            - Path=/api/v1/stores/**

        - id: coupon-service-api
          uri: http://coupon:8080 # Service Connect 이름
          predicates:
            - Path=/api/v1/owner/coupons/**
            - Path=/api/v1/coupons/**

# Actuator (Gateway 자체 헬스 체크)
management:
  endpoints:
    web:
      exposure:
        include: health # 헬스 체크만 노출 (info 등 불필요)