server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: # 구체적일수록 위에 작성하기
        # Member Service 헬스 체크 라우트 (서비스별로 하나씩 보유, e.g /api/v1/{서비스명}/actuator/health)
        - id: member-service-health
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/members/actuator/health # /api/v1/members/actuator/health 딱 이 경로만 매칭
          filters:
            - RewritePath=/api/v1/members/actuator/health, /actuator/health

        # Auth API 라우트
        - id: member-service-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/** # /api/v1/auth/ 로 시작하는 모든 경로 매칭
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /api/v1/auth/${segment}

        # Members API 라우트
        - id: member-service-members
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/members/** # /api/v1/members/ 로 시작하는 모든 경로 매칭
          filters:
            - RewritePath=/api/v1/members/(?<segment>.*), /api/v1/members/${segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG