server:
  port: 8080 # ECS Task Definition의 portMappings와 일치

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: # 구체적일수록 위에 작성하기
        # -----------------------------------------------
        # 1. Health Checks  (서비스별로 하나씩 보유, e.g /api/v1/{서비스명}/actuator/health)
        # -----------------------------------------------
        - id: member-service-health
          uri: http://member.couponpop.local:8080 # Service Connect의 "검색 이름" (예: member)으로 사용
          predicates:
            - Path=/health/member
          filters:
            - RewritePath=/health/member, /actuator/health

        - id: store-service-health
          uri: http://store.couponpop.local:8080
          predicates:
            - Path=/health/store
          filters:
            - RewritePath=/health/store, /actuator/health

        - id: coupon-service-health
          uri: http://coupon.couponpop.local:8080
          predicates:
            - Path=/health/coupon
          filters:
            - RewritePath=/health/coupon, /actuator/health

        - id: notification-service-health
          uri: http://notification.couponpop.local:8080
          predicates:
            - Path=/health/notification
          filters:
            - RewritePath=/health/notification, /actuator/health

        - id: batch-service-health
          uri: http://batch.couponpop.local:8080
          predicates:
            - Path=/health/batch
          filters:
            - RewritePath=/health/batch, /actuator/health

        # -----------------------------------------------
        # 2. General API Routes (범용 경로)
        # -----------------------------------------------
        # ===== Member Service =====
        - id: member-service-auth-api
          uri: http://member.couponpop.local:8080   # Service Connect 이름
          predicates:
            - Path=/api/v1/auth/**

        - id: member-service-member-api
          uri: http://member.couponpop.local:8080
          predicates:
            - Path=/api/v1/members/**

        # ===== Store Service =====
        - id: store-service-owner-api
          uri: http://store.couponpop.local:8080
          predicates:
            - Path=/api/v1/owner/stores/**

        - id: store-service-owners-api
          uri: http://store.couponpop.local:8080
          predicates:
            - Path=/api/v1/owners/**

        - id: store-service-api
          uri: http://store.couponpop.local:8080
          predicates:
            - Path=/api/v1/stores/**

        # ===== Coupon Service =====
        - id: coupon-service-owner-api
          uri: http://coupon.couponpop.local:8080
          predicates:
            - Path=/api/v1/owner/coupons/**

        - id: coupon-service-api
          uri: http://coupon.couponpop.local:8080
          predicates:
            - Path=/api/v1/coupons/**

        # ===== Notification Service =====
        - id: notification-service-fcm-token-api
          uri: http://notification.couponpop.local:8080
          predicates:
            - Path=/api/v1/fcm-token

management:
  endpoints:
    web:
      exposure:
        include: health # 헬스 체크만 노출