server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: # 구체적일수록 위에 작성하기
        # -----------------------------------------------
        # 1. Health Checks (서비스별로 하나씩 보유, e.g /api/v1/{서비스명}/actuator/health)
        # -----------------------------------------------
        - id: member-service-health
          uri: http://localhost:8081 # Member Service (8081)
          predicates:
            - Path=/api/v1/members/actuator/health
          filters:
            # /api/v1/members/actuator/health -> /actuator/health
            - RewritePath=/api/v1/members/actuator/health, /actuator/health

        - id: store-service-health
          uri: http://localhost:8082 # Store Service (8082)
          predicates:
            # Store Service 헬스 체크 경로 (패턴에 맞게 /api/v1/stores/actuator/health 로 가정)
            - Path=/api/v1/stores/actuator/health
          filters:
            # /api/v1/stores/actuator/health -> /actuator/health
            - RewritePath=/api/v1/stores/actuator/health, /actuator/health

        - id: coupon-service-health
          uri: http://localhost:8083 # Coupon Service (8083)
          predicates:
            # Coupon Service 헬스 체크 경로
            - Path=/api/v1/coupons/actuator/health
          filters:
            # /api/v1/coupons/actuator/health -> /actuator/health
            - RewritePath=/api/v1/coupons/actuator/health, /actuator/health
        # -----------------------------------------------
        # 2. General API Routes (범용 경로)
        # -----------------------------------------------
        - id: member-service-api
          uri: http://localhost:8081 # Member Service (8081)
          predicates:
            - Path=/api/v1/auth/**
            - Path=/api/v1/members/**
          # 필터 없음: /api/v1/members/profile -> http://localhost:8081/api/v1/members/profile

        - id: store-service-api
          uri: http://localhost:8082 # Store Service (8082)
          predicates:
            - Path=/api/v1/owner/stores/**
            - Path=/api/v1/stores/**
          # 필터 없음: /api/v1/stores/1 -> http://localhost:8082/api/v1/stores/1

        - id: coupon-service-api
          uri: http://localhost:8083 # Coupon Service (8083)
          predicates:
            - Path=/api/v1/owner/coupons/**
            - Path=/api/v1/coupons/**
          # 필터 없음: /api/v1/coupons/check -> http://localhost:8083/api/v1/coupons/check

          # Notification Service는 외부 API 호출 없음

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG